dist: bionic
language: go
env:
  - GO111MODULE="on"
  - FLYWAY_VERSION=8.0.2
  - INPUT_BUILDARGS=FLYWAY_VERSION=8.0.2
go:
  - 1.17.1
go_import_path: github.com/adevinta/vulcan-reports-generator
script:
  - go install -v $(go list ./... | grep -v /vendor/)
  - go test -v $(go list ./... | grep -v /vendor/)
  - cd cmd/vulcan-reports-generator && go build && cd ../..
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
