dist: bionic
language: go
env:
  global:
    - FLYWAY_VERSION=9.1.4
    - INPUT_BUILDARGS=FLYWAY_VERSION=9.1.4
go:
  - 1.18.x
go_import_path: github.com/adevinta/vulcan-reports-generator
script:
  - go install -v $(go list ./... | grep -v /vendor/)
  - go test -v $(go list ./... | grep -v /vendor/)
  - cd cmd/vulcan-reports-generator && go build && cd ../..
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
