dist: bionic
language: go
go:
  - 1.13.3
cache:
  directories:
    - "vendor/"
go_import_path: github.com/adevinta/vulcan-reports-generator
before_install:
  - rm -rf vendor/github.com/adevinta/security-overview
install: _script/bootstrap
script: _script/cibuild
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
