[log]
# log levels: panic, fatal, error, warn, info, debug, trace
level ="$LOG_LEVEL"
# indicates if method caller must be logged
add_caller = false

[api]
port = $PORT

[db]
dialect = "postgres"
host = "$PG_HOST"
port = "$PG_PORT"
user = "$PG_USER"
password = "$PG_PASSWORD"
sslmode = "$PG_SSLMODE"
name = "$PG_NAME"

[sqs]
number_of_processors = $SQS_NUM_PROCESSORS
wait_time = 20
timeout = 3600
queue_arn = "$SQS_QUEUE_ARN"
endpoint = "$AWS_SQS_ENDPOINT"

[ses]
region = "$SES_REGION"
from = "$SES_FROM"
cc = $SES_CC

[generators]

    [generators.livereport]
    email_subject = "$LIVEREPORT_EMAIL_SUBJECT"
    email_template_file = "/app/resources/generators/livereport/resources/template"
