// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package storage

var TableNames = struct {
	LiveReports string
	ScanReports string
}{
	LiveReports: "live_reports",
	ScanReports: "scan_reports",
}
