// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package storage

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// LiveReport is an object representing the database table.
type LiveReport struct {
	ID             string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	EmailSubject   string    `boil:"email_subject" json:"email_subject" toml:"email_subject" yaml:"email_subject"`
	EmailBody      string    `boil:"email_body" json:"email_body" toml:"email_body" yaml:"email_body"`
	TeamID         string    `boil:"team_id" json:"team_id" toml:"team_id" yaml:"team_id"`
	DateTo         string    `boil:"date_to" json:"date_to" toml:"date_to" yaml:"date_to"`
	DateFrom       string    `boil:"date_from" json:"date_from" toml:"date_from" yaml:"date_from"`
	DeliveredTo    string    `boil:"delivered_to" json:"delivered_to" toml:"delivered_to" yaml:"delivered_to"`
	UpdateStatusAt time.Time `boil:"update_status_at" json:"update_status_at" toml:"update_status_at" yaml:"update_status_at"`
	Status         string    `boil:"status" json:"status" toml:"status" yaml:"status"`
	CreatedAt      time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt      time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *liveReportR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L liveReportL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var LiveReportColumns = struct {
	ID             string
	EmailSubject   string
	EmailBody      string
	TeamID         string
	DateTo         string
	DateFrom       string
	DeliveredTo    string
	UpdateStatusAt string
	Status         string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "id",
	EmailSubject:   "email_subject",
	EmailBody:      "email_body",
	TeamID:         "team_id",
	DateTo:         "date_to",
	DateFrom:       "date_from",
	DeliveredTo:    "delivered_to",
	UpdateStatusAt: "update_status_at",
	Status:         "status",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var LiveReportWhere = struct {
	ID             whereHelperstring
	EmailSubject   whereHelperstring
	EmailBody      whereHelperstring
	TeamID         whereHelperstring
	DateTo         whereHelperstring
	DateFrom       whereHelperstring
	DeliveredTo    whereHelperstring
	UpdateStatusAt whereHelpertime_Time
	Status         whereHelperstring
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpertime_Time
}{
	ID:             whereHelperstring{field: "\"live_reports\".\"id\""},
	EmailSubject:   whereHelperstring{field: "\"live_reports\".\"email_subject\""},
	EmailBody:      whereHelperstring{field: "\"live_reports\".\"email_body\""},
	TeamID:         whereHelperstring{field: "\"live_reports\".\"team_id\""},
	DateTo:         whereHelperstring{field: "\"live_reports\".\"date_to\""},
	DateFrom:       whereHelperstring{field: "\"live_reports\".\"date_from\""},
	DeliveredTo:    whereHelperstring{field: "\"live_reports\".\"delivered_to\""},
	UpdateStatusAt: whereHelpertime_Time{field: "\"live_reports\".\"update_status_at\""},
	Status:         whereHelperstring{field: "\"live_reports\".\"status\""},
	CreatedAt:      whereHelpertime_Time{field: "\"live_reports\".\"created_at\""},
	UpdatedAt:      whereHelpertime_Time{field: "\"live_reports\".\"updated_at\""},
}

// LiveReportRels is where relationship names are stored.
var LiveReportRels = struct {
}{}

// liveReportR is where relationships are stored.
type liveReportR struct {
}

// NewStruct creates a new relationship struct
func (*liveReportR) NewStruct() *liveReportR {
	return &liveReportR{}
}

// liveReportL is where Load methods for each relationship are stored.
type liveReportL struct{}

var (
	liveReportAllColumns            = []string{"id", "email_subject", "email_body", "team_id", "date_to", "date_from", "delivered_to", "update_status_at", "status", "created_at", "updated_at"}
	liveReportColumnsWithoutDefault = []string{"status"}
	liveReportColumnsWithDefault    = []string{"id", "email_subject", "email_body", "team_id", "date_to", "date_from", "delivered_to", "update_status_at", "created_at", "updated_at"}
	liveReportPrimaryKeyColumns     = []string{"id"}
)

type (
	// LiveReportSlice is an alias for a slice of pointers to LiveReport.
	// This should generally be used opposed to []LiveReport.
	LiveReportSlice []*LiveReport

	liveReportQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	liveReportType                 = reflect.TypeOf(&LiveReport{})
	liveReportMapping              = queries.MakeStructMapping(liveReportType)
	liveReportPrimaryKeyMapping, _ = queries.BindMapping(liveReportType, liveReportMapping, liveReportPrimaryKeyColumns)
	liveReportInsertCacheMut       sync.RWMutex
	liveReportInsertCache          = make(map[string]insertCache)
	liveReportUpdateCacheMut       sync.RWMutex
	liveReportUpdateCache          = make(map[string]updateCache)
	liveReportUpsertCacheMut       sync.RWMutex
	liveReportUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single liveReport record from the query using the global executor.
func (q liveReportQuery) OneG(ctx context.Context) (*LiveReport, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single liveReport record from the query.
func (q liveReportQuery) One(ctx context.Context, exec boil.ContextExecutor) (*LiveReport, error) {
	o := &LiveReport{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "storage: failed to execute a one query for live_reports")
	}

	return o, nil
}

// AllG returns all LiveReport records from the query using the global executor.
func (q liveReportQuery) AllG(ctx context.Context) (LiveReportSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all LiveReport records from the query.
func (q liveReportQuery) All(ctx context.Context, exec boil.ContextExecutor) (LiveReportSlice, error) {
	var o []*LiveReport

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "storage: failed to assign all query results to LiveReport slice")
	}

	return o, nil
}

// CountG returns the count of all LiveReport records in the query, and panics on error.
func (q liveReportQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all LiveReport records in the query.
func (q liveReportQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "storage: failed to count live_reports rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table, and panics on error.
func (q liveReportQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q liveReportQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "storage: failed to check if live_reports exists")
	}

	return count > 0, nil
}

// LiveReports retrieves all the records using an executor.
func LiveReports(mods ...qm.QueryMod) liveReportQuery {
	mods = append(mods, qm.From("\"live_reports\""))
	return liveReportQuery{NewQuery(mods...)}
}

// FindLiveReportG retrieves a single record by ID.
func FindLiveReportG(ctx context.Context, iD string, selectCols ...string) (*LiveReport, error) {
	return FindLiveReport(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindLiveReport retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindLiveReport(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*LiveReport, error) {
	liveReportObj := &LiveReport{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"live_reports\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, liveReportObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "storage: unable to select from live_reports")
	}

	return liveReportObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *LiveReport) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *LiveReport) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("storage: no live_reports provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(liveReportColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	liveReportInsertCacheMut.RLock()
	cache, cached := liveReportInsertCache[key]
	liveReportInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			liveReportAllColumns,
			liveReportColumnsWithDefault,
			liveReportColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(liveReportType, liveReportMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(liveReportType, liveReportMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"live_reports\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"live_reports\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "storage: unable to insert into live_reports")
	}

	if !cached {
		liveReportInsertCacheMut.Lock()
		liveReportInsertCache[key] = cache
		liveReportInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single LiveReport record using the global executor.
// See Update for more documentation.
func (o *LiveReport) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the LiveReport.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *LiveReport) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	liveReportUpdateCacheMut.RLock()
	cache, cached := liveReportUpdateCache[key]
	liveReportUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			liveReportAllColumns,
			liveReportPrimaryKeyColumns,
		)

		if len(wl) == 0 {
			return 0, errors.New("storage: unable to update live_reports, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"live_reports\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, liveReportPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(liveReportType, liveReportMapping, append(wl, liveReportPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "storage: unable to update live_reports row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "storage: failed to get rows affected by update for live_reports")
	}

	if !cached {
		liveReportUpdateCacheMut.Lock()
		liveReportUpdateCache[key] = cache
		liveReportUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q liveReportQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q liveReportQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "storage: unable to update all for live_reports")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "storage: unable to retrieve rows affected for live_reports")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o LiveReportSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o LiveReportSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("storage: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), liveReportPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"live_reports\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, liveReportPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "storage: unable to update all in liveReport slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "storage: unable to retrieve rows affected all in update all liveReport")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *LiveReport) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *LiveReport) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("storage: no live_reports provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(liveReportColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	liveReportUpsertCacheMut.RLock()
	cache, cached := liveReportUpsertCache[key]
	liveReportUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			liveReportAllColumns,
			liveReportColumnsWithDefault,
			liveReportColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			liveReportAllColumns,
			liveReportPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("storage: unable to upsert live_reports, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(liveReportPrimaryKeyColumns))
			copy(conflict, liveReportPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"live_reports\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(liveReportType, liveReportMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(liveReportType, liveReportMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "storage: unable to upsert live_reports")
	}

	if !cached {
		liveReportUpsertCacheMut.Lock()
		liveReportUpsertCache[key] = cache
		liveReportUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single LiveReport record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *LiveReport) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single LiveReport record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *LiveReport) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("storage: no LiveReport provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), liveReportPrimaryKeyMapping)
	sql := "DELETE FROM \"live_reports\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "storage: unable to delete from live_reports")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "storage: failed to get rows affected by delete for live_reports")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q liveReportQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("storage: no liveReportQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "storage: unable to delete all from live_reports")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "storage: failed to get rows affected by deleteall for live_reports")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o LiveReportSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o LiveReportSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), liveReportPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"live_reports\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, liveReportPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "storage: unable to delete all from liveReport slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "storage: failed to get rows affected by deleteall for live_reports")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *LiveReport) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("storage: no LiveReport provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *LiveReport) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindLiveReport(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *LiveReportSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("storage: empty LiveReportSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *LiveReportSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := LiveReportSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), liveReportPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"live_reports\".* FROM \"live_reports\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, liveReportPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "storage: unable to reload all in LiveReportSlice")
	}

	*o = slice

	return nil
}

// LiveReportExistsG checks if the LiveReport row exists.
func LiveReportExistsG(ctx context.Context, iD string) (bool, error) {
	return LiveReportExists(ctx, boil.GetContextDB(), iD)
}

// LiveReportExists checks if the LiveReport row exists.
func LiveReportExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"live_reports\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "storage: unable to check if live_reports exists")
	}

	return exists, nil
}
